(def x (read-line))
(cond
  (= (Integer. x) 1) (println "January")
  (= (Integer. x) 2) (println "February")
  (= (Integer. x) 3) (println "March")
  (= (Integer. x) 4) (println "April")
  (= (Integer. x) 5) (println "May")
  (= (Integer. x) 6) (println "June")
  (= (Integer. x) 7) (println "July")
  (= (Integer. x) 8) (println "August")
  (= (Integer. x) 9) (println "September")
  (= (Integer. x) 10) (println "October")
  (= (Integer. x) 11) (println "November")
  (= (Integer. x) 12) (println "December"))
